const {_electron: electron} = require('playwright')
const path = require('node:path')
const fs = require('node:fs/promises')
const {execFileSync} = require('node:child_process')
const assert = require('node:assert/strict')

async function main() {
  const root = path.resolve(__dirname, '..')
  const evaluation = {}
  const ts = require('typescript')
  require('node:vm').runInNewContext(ts.transpileModule(await fs.readFile(path.join(root, 'desktop/src/analysis/evaluation.ts'), 'utf8'), {
    compilerOptions: {module: ts.ModuleKind.CommonJS}
  }).outputText, {exports: evaluation})
  const candidates = [10, 9.4, 8.4, 6.9, 3.9].map(score_lead => ({score_lead, winrate: .71}))
  assert.equal(new Set(candidates.map(c => evaluation.lossColor(evaluation.candidateLoss(c, candidates)))).size, 5)
  assert.equal(evaluation.candidateLoss(candidates[0], candidates), 0)
  assert.equal(evaluation.lossColor(.5), evaluation.LOSS_LEVELS[1].color)
  assert.equal(evaluation.lossColor(6), evaluation.LOSS_LEVELS[4].color)
  const runtime = path.join(root, '.runtime')
  await fs.mkdir(runtime, {recursive: true})
  const directory = await fs.mkdtemp(path.join(runtime, 'workbench-test-'))
  let server
  if (process.env.LLMGO_TEST_DEV || process.argv.includes('--dev')) {
    const {createServer} = await import('vite')
    server = await createServer({server: {port: 5173}})
    await server.listen()
  }
  const env = {...process.env, LLMGO_USER_DATA: directory, PYTHONUTF8: '1', ...(server ? {LLMGO_DEV_URL: 'http://127.0.0.1:5173'} : {})}
  delete env.ELECTRON_RUN_AS_NODE
  delete env.OPENAI_API_KEY
  const application = await electron.launch({args: [root], env, timeout: 60000})
  const checks = [], errors = []
  let descendants = []
  let page
  const menu = async action => {
    await page.waitForFunction(() => !document.querySelector('.navigation button')?.disabled)
    await application.evaluate(({BrowserWindow}, name) => BrowserWindow.getAllWindows()[0].webContents.send('llmgo:menu', name), action)
  }
  const shortcut = async accelerator => {
    await application.evaluate(({Menu, BrowserWindow}, key) => {
      if (key === 'F4') {
        const window = BrowserWindow.getAllWindows()[0]
        window.webContents.sendInputEvent({type: 'keyDown', keyCode: key})
        window.webContents.sendInputEvent({type: 'keyUp', keyCode: key})
        return
      }
      const item = Menu.getApplicationMenu().items.flatMap(item => item.submenu?.items || []).find(item => item.accelerator === key)
      if (!item) throw new Error(`Missing accelerator ${key}`)
      item.click()
    }, accelerator)
    await page.waitForTimeout(100)
  }
  const watchSize = async () => page.evaluate(() => {
    const box = document.querySelector('#main-goban').getBoundingClientRect()
    window.boardSizes = []
    window.expectedSize = {width: box.width, height: box.height}
    window.sizeObserver?.disconnect()
    window.sizeObserver = new ResizeObserver(() => {
      const b = document.querySelector('#main-goban').getBoundingClientRect()
      window.boardSizes.push({width: b.width, height: b.height})
    })
    window.sizeObserver.observe(document.querySelector('#main-goban'))
  })
  const assertStable = async label => {
    await page.waitForTimeout(100)
    const metrics = await page.evaluate(() => ({expected: window.expectedSize, sizes: window.boardSizes}))
    assert.ok(metrics.sizes.every(b => Math.abs(b.width - metrics.expected.width) < .1 && Math.abs(b.height - metrics.expected.height) < .1), `${label}: ${JSON.stringify(metrics)}`)
    checks.push(`stable board: ${label}`)
  }
  const drag = async (label, dx, dy) => {
    const box = await page.getByRole('separator', {name: label, exact: true}).boundingBox()
    await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2)
    await page.mouse.down()
    for (let step = 1; step <= 10; step++) {
      await page.mouse.move(box.x + box.width / 2 + dx * step / 10, box.y + box.height / 2 + dy * step / 10)
      await page.waitForTimeout(20)
    }
    await page.mouse.up()
    await page.waitForTimeout(100)
  }
  try {
    page = await application.firstWindow({timeout: 60000})
    await application.evaluate(({BrowserWindow}) => {
      const window = BrowserWindow.getAllWindows()[0]
      window.setSkipTaskbar(true); window.setIgnoreMouseEvents(true); window.hide()
      window.webContents.setBackgroundThrottling(false)
    })
    assert.equal(await application.evaluate(({Menu}) => Menu.getApplicationMenu().items.flatMap(item => item.submenu?.items || []).some(item => item.label === '切换手数显示')), false)
    page.on('pageerror', error => errors.push(error.message))
    const board = page.locator('#main-goban')
    await board.waitFor()
    assert.equal(await page.locator('header').count(), 0)
    assert.equal(await page.locator('.board-heading,.board-options,.candidates,.candidate,.loss-legend,.players,.drop-hint,.preview-bar').count(), 0)
    assert.equal(await page.getByText('19 路', {exact: true}).count(), 0)
    assert.equal(await page.locator('.shudan-vertex').count(), 361)
    await page.waitForFunction(async () => ['starting', 'ready'].includes((await window.llmgo.invoke('health')).katago))
    checks.push('renderer ready automatically initializes KataGo')
    const source = path.join(directory, 'fixture.sgf')
    await fs.writeFile(source, '(;CA[UTF-8]SZ[19]PB[Black Player]PW[White Player]KM[7.5]RU[Japanese]AB[cc]' + Array.from({length: 110}, (_, i) => `;${i % 2 ? 'W' : 'B'}[${i === 0 ? 'aa' : ''}]`).join('') + ')')
    await application.evaluate(({dialog}, file) => {dialog.showOpenDialog = async () => ({canceled: false, filePaths: [file]})}, source)
    await menu('open')
    await page.getByText('fixture.sgf', {exact: true}).waitFor()
    await page.getByRole('button', {name: '最后一手', exact: true}).click()
    await page.waitForFunction(() => document.querySelector('.navigation b').textContent.includes('110'))
    await page.evaluate(() => {
      window.boardIdentity = document.querySelector('#main-goban')
      window.treeIdentity = document.querySelector('[role=treeitem]')
      window.busyFlashes = 0
      window.observer = new MutationObserver(() => {if (window.boardIdentity.classList.contains('shudan-busy')) window.busyFlashes++})
      window.observer.observe(window.boardIdentity, {attributes: true, attributeFilter: ['class']})
      window.soundCount = 0
      const start = AudioBufferSourceNode.prototype.start
      AudioBufferSourceNode.prototype.start = function (...args) {
        window.soundCount++
        window.sample = {duration: this.buffer.duration, state: this.context.state, peak: Math.max(...this.buffer.getChannelData(0))}
        return start.apply(this, args)
      }
    })
    const vertex = (x, y) => page.locator(`.shudan-vertex[data-x="${x}"][data-y="${y}"]`)
    const label = (x, y) => vertex(x, y).locator('.shudan-marker')
    await watchSize()
    await vertex(3, 15).click() // B D4 = 111
    await page.waitForFunction(() => document.querySelector('.navigation b').textContent.includes('111'))
    assert.equal(await label(3, 15).textContent(), '')
    await shortcut('F4')
    assert.equal(await label(3, 15).textContent(), '111')
    await vertex(4, 15).click() // W E4 = 112
    await page.waitForFunction(() => document.querySelector('.navigation b').textContent.includes('112'))
    assert.equal(await label(4, 15).textContent(), '112')
    assert.equal(await label(3, 15).count(), 0)
    await shortcut('F4')
    assert.equal(await label(0, 0).textContent(), '1')
    assert.equal(await label(3, 15).textContent(), '111')
    await vertex(5, 15).click()
    await page.waitForFunction(() => document.querySelector('.navigation b').textContent.includes('113'))
    assert.equal(await label(5, 15).textContent(), '113')
    assert.equal(await label(2, 2).count(), 0) // setup never numbered
    for (const [x, expected] of [[3, 'rgb(255, 255, 255)'], [4, 'rgb(0, 0, 0)']]) {
      const metrics = await label(x, 15).evaluate(el => {
        const marker = el.getBoundingClientRect(), cell = el.parentElement.getBoundingClientRect()
        return {color: getComputedStyle(el).color, centered: Math.hypot(marker.x + marker.width / 2 - cell.x - cell.width / 2, marker.y + marker.height / 2 - cell.y - cell.height / 2), fits: el.scrollWidth <= el.clientWidth}
      })
      assert.equal(metrics.color, expected); assert.ok(metrics.centered < 1 && metrics.fits)
    }
    await shortcut('F4')
    assert.equal(await board.locator('.shudan-marker_label').count(), 0)
    await assertStable('move numbers and real moves')
    checks.push('off/latest/all cycle; 111/112/113 share SGF numbering; setup excluded; black/white contrast; centered 3 digits')
    await page.waitForFunction(() => window.soundCount === 3)
    const sample = await page.evaluate(() => window.sample)
    assert.ok(sample.duration > .02 && sample.peak > .01 && sample.state === 'running', JSON.stringify(sample))
    await page.getByRole('button', {name: '前一手', exact: true}).click()
    await page.waitForFunction(() => document.querySelector('.navigation b').textContent.includes('112'))
    assert.equal(await page.evaluate(() => window.soundCount), 3)
    await vertex(5, 15).click() // Entering an existing successor also plays one sound.
    await page.waitForFunction(() => window.soundCount === 4)
    await page.waitForFunction(() => document.querySelector('.navigation b').textContent === '113')
    await page.getByRole('button', {name: '停一手', exact: true}).click()
    await page.waitForFunction(() => document.querySelector('.navigation b').textContent === '114')
    assert.equal(await page.evaluate(() => window.soundCount), 4)
    await page.getByRole('button', {name: '前一手', exact: true}).click()
    await page.waitForFunction(() => document.querySelector('.navigation b').textContent === '113')
    await page.getByRole('button', {name: '前一手', exact: true}).click()
    await page.waitForFunction(() => document.querySelector('.navigation b').textContent === '112')
    assert.ok(await page.evaluate(() => window.boardIdentity === document.querySelector('#main-goban') && window.treeIdentity === document.querySelector('[role=treeitem]') && !window.busyFlashes))
    checks.push('navigation retains board/tree DOM with no busy flash; forward stone sounds once, pass/backward silent')
    const before = await board.boundingBox()
    await page.getByRole('button', {name: '折叠棋谱栏'}).click()
    await page.getByRole('button', {name: '折叠 AI 栏'}).click()
    await page.waitForFunction(() => document.querySelector('.workspace').classList.contains('right-collapsed'))
    await page.waitForTimeout(100)
    const after = await board.boundingBox()
    assert.ok(after.width >= before.width && Math.abs(after.width - after.height) < 1)
    await application.evaluate(({BrowserWindow}) => BrowserWindow.getAllWindows()[0].setSize(1150, 780))
    await page.waitForTimeout(150)
    const smaller = await board.boundingBox()
    const space = await page.locator('.board-space').boundingBox()
    assert.ok(smaller.width <= space.width && smaller.height <= space.height && Math.abs(smaller.width - smaller.height) < 1, JSON.stringify({before, after, smaller, space}))
    assert.ok(await page.evaluate(() => window.boardIdentity === document.querySelector('#main-goban')))
    await page.getByRole('button', {name: '展开棋谱栏'}).click()
    await page.getByRole('button', {name: '展开 AI 栏'}).click()
    await page.waitForTimeout(150)
    const bounds = async selector => page.locator(selector).boundingBox()
    const leftBefore = await bounds('.game-panel'), rightBefore = await bounds('.teacher-panel')
    await drag('调整棋谱栏宽度', 70, 0)
    await drag('调整 AI 栏宽度', -50, 0)
    const leftAfter = await bounds('.game-panel'), rightAfter = await bounds('.teacher-panel'), center = await bounds('.board-panel')
    assert.ok(leftAfter.width > leftBefore.width + 50 && rightAfter.width > rightBefore.width + 30, JSON.stringify({leftBefore, leftAfter, rightBefore, rightAfter}))
    assert.ok(leftAfter.x + leftAfter.width <= center.x && rightAfter.x >= center.x + center.width)
    const resized = await board.boundingBox()
    assert.ok(Math.abs(resized.width - resized.height) < 1)
    await page.getByRole('button', {name: '折叠棋谱栏'}).click()
    await page.getByRole('button', {name: '展开棋谱栏'}).click()
    await page.waitForTimeout(150)
    assert.equal((await bounds('.game-panel')).width, leftAfter.width)
    const treeBefore = await bounds('.tree-list')
    const verticalBefore = await page.locator('.tree-section,.comment,.splitter-row').evaluateAll(elements => elements.map(el => ({class: el.className, height: el.getBoundingClientRect().height, value: el.getAttribute('aria-valuenow'), scroll: el.scrollTop})))
    await watchSize()
    await drag('调整棋局信息高度', 0, -120)
    await drag('调整注释区域高度', 0, 105)
    const treeAfter = await bounds('.tree-list')
    assert.ok(treeAfter.height > treeBefore.height + 160, JSON.stringify({treeBefore, treeAfter, verticalBefore, verticalAfter: await page.locator('.tree-section,.comment,.splitter-row').evaluateAll(elements => elements.map(el => ({class: el.className, height: el.getBoundingClientRect().height, value: el.getAttribute('aria-valuenow'), scroll: el.scrollTop})))}))
    await assertStable('vertical tree resizing')
    await drag('调整注释区域高度', 0, -120)
    await drag('调整棋局信息高度', 0, 125)
    await drag('调整棋谱栏宽度', -70, 0)
    await drag('调整 AI 栏宽度', 50, 0)
    checks.push('sidebars drag/collapse/restore without overlap; square board; both tree splitters')
    await page.getByRole('treeitem', {name: '第 109 手 B pass', exact: true}).click()
    await page.waitForFunction(() => document.querySelector('.navigation b').textContent.includes('109'))
    await vertex(6, 15).click()
    await page.waitForFunction(() => document.querySelector('.navigation b').textContent.includes('110'))
    const state = await page.evaluate(() => window.llmgo.invoke('state'))
    const parent = state.nodes.find(n => n.id === state.nodes.find(n => n.id === state.node_id).parent_id)
    assert.equal(parent.children.length, 2)
    const edited = state.node_id
    await page.getByLabel('棋谱注释', {exact: true}).fill('新增变化 ] 中文注释')
    await page.getByRole('button', {name: '保存注释', exact: true}).click()
    await page.waitForFunction(async () => (await window.llmgo.invoke('state')).comment === '新增变化 ] 中文注释')
    await menu('deleteBranch')
    await page.waitForFunction(async id => !(await window.llmgo.invoke('state')).nodes.some(n => n.id === id), edited)
    await menu('undo')
    await page.waitForFunction(async id => (await window.llmgo.invoke('state')).node_id === id, edited)
    await menu('redo')
    await page.waitForFunction(async id => !(await window.llmgo.invoke('state')).nodes.some(n => n.id === id), edited)
    await menu('undo')
    await page.waitForFunction(async id => (await window.llmgo.invoke('state')).node_id === id, edited)
    const saved = path.join(directory, 'saved.sgf')
    await application.evaluate(({dialog}, target) => {dialog.showSaveDialog = async () => ({canceled: false, filePath: target})}, saved)
    await menu('saveAs')
    await page.getByRole('alert').filter({hasText: '已保存'}).waitFor()
    assert.ok((await fs.readFile(saved, 'utf8')).includes('新增变化'))
    checks.push('historical click creates real variation; comment save; native delete/undo/redo/save menus')
    await menu('apiSettings')
    await page.getByLabel('Provider').selectOption('deepseek')
    assert.equal(await page.getByLabel('Base URL', {exact: true}).inputValue(), 'https://api.deepseek.com')
    await page.getByLabel('Provider').selectOption('compatible')
    await page.getByLabel('Base URL', {exact: true}).fill('http://localhost:8000/v1')
    await page.getByLabel('Model', {exact: true}).fill('test-model')
    await page.getByRole('button', {name: '保存设置', exact: true}).click()
    await page.getByText('设置已保存', {exact: true}).waitFor()
    assert.equal((await page.evaluate(() => window.llmgo.invoke('settings'))).provider, 'compatible')
    await page.getByRole('button', {name: '界面设置', exact: true}).click()
    assert.equal(await page.getByLabel('手数显示').inputValue(), 'off')
    await page.getByLabel('手数显示').selectOption('all')
    await page.waitForFunction(async () => (await window.llmgo.invoke('settings')).move_number_mode === 'all')
    assert.ok(await board.locator('.shudan-marker_label').count() > 0)
    await shortcut('F4')
    assert.equal(await page.getByLabel('手数显示').inputValue(), 'off')
    await page.waitForFunction(async () => (await window.llmgo.invoke('settings')).move_number_mode === 'off')
    await page.getByLabel('落子音效').selectOption('false')
    await page.getByRole('button', {name: '保存设置', exact: true}).click()
    await page.getByText('设置已保存', {exact: true}).waitFor()
    await page.getByRole('button', {name: '关闭设置'}).click()
    const persisted = JSON.parse(await fs.readFile(path.join(directory, 'settings.json'), 'utf8'))
    assert.equal(persisted.move_number_mode, 'off')
    assert.equal(persisted.sound_enabled, false)
    await menu('interfaceSettings')
    await page.getByLabel('落子音效').selectOption('true')
    await page.getByRole('button', {name: '保存设置', exact: true}).click()
    await page.getByText('设置已保存', {exact: true}).waitFor()
    await page.getByRole('button', {name: '关闭设置'}).click()
    checks.push('split settings; DeepSeek preset; compatible URL/model persisted; sound setting')
    let health
    const deadline = Date.now() + 240000
    do {
      health = await page.evaluate(() => window.llmgo.invoke('health'))
      if (health.katago === 'ready' || health.katago === 'error') break
      await page.waitForTimeout(500)
    } while (Date.now() < deadline)
    assert.equal(health.katago, 'ready', health.error)
    const analysisState = await page.evaluate(() => window.llmgo.invoke('state'))
    assert.equal(analysisState.node_id, edited, JSON.stringify({edited, current: analysisState.node_id, move: analysisState.move_number}))
    await watchSize()
    await shortcut('F5')
    await page.waitForFunction(() => !document.querySelector('.statusbar').textContent.includes('Visits —'), null, {timeout: 240000})
    const analyzedState = await page.evaluate(() => window.llmgo.invoke('state'))
    assert.ok(analyzedState.move_losses[edited] >= 0, JSON.stringify({edited, current: analyzedState.node_id, move: analyzedState.move_number, losses: analyzedState.move_losses, last: analyzedState.nodes.slice(-2)}))
    await assertStable('analysis start/completion and candidate appearance')
    const recommendation = page.locator('.recommendation').first()
    assert.match(await recommendation.textContent(), /\d+\.\d%[+-]\d+\.\d/)
    assert.ok(Number(await recommendation.getAttribute('data-level')) >= 0)
    assert.equal(await recommendation.evaluate(el => getComputedStyle(el).pointerEvents), 'none')
    const coordinate = await recommendation.getAttribute('data-coordinate')
    const point = vertex('ABCDEFGHJKLMNOPQRST'.indexOf(coordinate[0]), 19 - Number(coordinate.slice(1)))
    const [overlayBox, pointBox] = await Promise.all([recommendation.boundingBox(), point.boundingBox()])
    assert.ok(Math.abs(overlayBox.x + overlayBox.width / 2 - pointBox.x - pointBox.width / 2) < 1)
    assert.ok(Math.abs(overlayBox.y + overlayBox.height / 2 - pointBox.y - pointBox.height / 2) < 1)
    const soundsBeforePreview = await page.evaluate(() => window.soundCount)
    await point.click({button: 'right'})
    await page.getByRole('button', {name: '返回当前局面 · PV 预览'}).waitFor({timeout: 180000})
    await assertStable('PV open')
    await page.getByRole('button', {name: '返回当前局面 · PV 预览'}).click()
    await assertStable('PV close')
    assert.equal(await page.evaluate(() => window.soundCount), soundsBeforePreview)
    await point.click()
    await page.waitForFunction(() => !document.querySelector('.recommendation'))
    assert.equal((await page.evaluate(() => window.llmgo.invoke('state'))).board_state.last_move, coordinate)
    await page.waitForFunction(count => window.soundCount === count + 1, soundsBeforePreview)
    await assertStable('left click on recommendation creates real SGF move')
    await shortcut('F6')
    await page.waitForFunction(() => /自动|分析中/.test(document.querySelector('.statusbar').textContent))
    await shortcut('F6')
    await page.waitForFunction(() => !/自动|分析中/.test(document.querySelector('.statusbar').textContent))
    await assertStable('F6 start/stop and cancellation')
    await page.getByRole('button', {name: '前一手', exact: true}).click()
    await page.waitForFunction(() => document.querySelector('.statusbar').textContent.includes('Visits —'))
    assert.equal(await page.locator('.recommendation').count(), 0)
    await assertStable('navigation clears analysis')
    checks.push('real startup/search/PV; score-loss coloring; navigation clears stale analysis')
    const processes = JSON.parse(execFileSync('powershell.exe', ['-NoProfile', '-Command', 'Get-CimInstance Win32_Process | Select-Object ProcessId,ParentProcessId,Name | ConvertTo-Json -Compress'], {encoding: 'utf8', windowsHide: true}))
    const ids = new Set([application.process().pid])
    let changed = true
    while (changed) {changed = false; for (const process of processes) if (ids.has(process.ParentProcessId) && !ids.has(process.ProcessId)) {ids.add(process.ProcessId); changed = true}}
    descendants = processes.filter(process => ids.has(process.ProcessId) && /python|katago|llmgo-core/i.test(process.Name))
    assert.ok(descendants.some(process => /katago/i.test(process.Name)))
    assert.deepEqual(errors, [])
    console.log(JSON.stringify({result: 'passed', checks, rendererErrors: errors}, null, 2))
  } catch (error) {
    if (page && !page.isClosed()) console.error('Desktop failure context:', await page.evaluate(() => ({url: location.href, status: document.querySelector('.statusbar')?.textContent, alert: document.querySelector('[role=alert]')?.textContent})), errors)
    throw error
  } finally {
    await application.close()
    await server?.close()
    const resolved = path.resolve(directory)
    assert.ok(resolved.startsWith(path.resolve(runtime) + path.sep) && path.basename(resolved).startsWith('workbench-test-'))
    await fs.rm(resolved, {recursive: true, force: true})
  }
  const surviving = descendants.filter(process => {try {global.process.kill(process.ProcessId, 0); return true} catch {return false}})
  assert.deepEqual(surviving, [], 'Python and KataGo terminate with the app')
  console.log('Process shutdown and temporary-file cleanup passed')
}
main().catch(error => {console.error(error); process.exitCode = 1})
